name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true
          clean-exclude: |
            **/*.js
            **/*.css
            **/*.map
            **/*.html
            **/*.json
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif
            **/*.svg
            **/*.woff
            **/*.woff2
            **/*.ttf
            **/*.eot
            CNAME
            .nojekyll
            404.html
